### ISSUE TITLE
Nested tags

### ISSUE THREAD

**Issue by arialdomartini** [tslilc/siege-mode#5]
This is an impressive mode!

I noticed that in the demo animated gif that after

```
\leftsiege-mode\right
```

inputing ```(``` produces:

```
\left(siege-mode\right)
```

I think the proper output should be:

```
\left(siege-mode)\right
```

Is there a way to configure siege-mode so it behaves like this?

**Comment by tslilc** [comment]
Thanks for writing! This behaviour is intentional; i wrote this with TeX in mind wherein delimiters for expressions are matched by `\leftX <expr> \rightX` for various values of `X` so in that sense it's correct.

But the good news is that it may be customised. See the variable `siege-boundary-list` and associated documentation, implemented [around here](https://github.com/tslilc/siege-mode/blob/master/siege-mode.el#L70)

Hope that helps

**Comment by arialdomartini** [comment]
Cool! Yes, this helps. I'm closing the issue!

Out of my curiosity, should the demo Gif display:

```
\left(siege-mode\right(
```

or

```
\left(siege-mode\right)
```

like it is showing? Is the latter what you meant?

**Comment by tslilc** [comment]
I believe the demo gif is displaying things in the intended fashion for TeX, so it should be \left( matching to \right)
